run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - goimports
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - dupl
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Exclude known issues in generated code
    - path: ".*\\.pb\\.go"
      linters:
        - all

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
