# Ollama Service Compose Template
# Story T-006: Compose-Template: Ollama Service (Health & Ports)

services:
  ollama:
    image: ollama/ollama:latest
    container_name: aistack-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - aistack-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - OLLAMA_HOST=0.0.0.0:11434

# Include common definitions
networks:
  aistack-net:
    external: true

volumes:
  ollama_data:
    external: true
